title: WhiteSpike
description: >-
              <b> Programmer for Fun </b> <br>

author:
  name: WhiteSpike
  image: imgs/WhiteSpike.png
  email: b.m.v.cabrita@gmail.com
  github: WhiteSpike

nav_exclude:
  - pages/index.md

collections:
  projects:
    output: true

exclude:
  - README.md

sass:
  quiet_deps: true