title: WhiteSpike's Portfolio
description: Main page where I post the projects I have done or doing

author:
  name: WhiteSpike
  image: imgs/WhiteSpike.png
  email: b.m.v.cabrita@gmail.com
  github: WhiteSpike

exclude:
  - README.md
